import { Toaster } from '@/components/ui/sonner';
import { ApolloWrapper } from '@/lib/graphql/apollo-wrapper';
import { AuthRedirectListener } from '@/lib/listeners/AuthRedirectListener';
import { ReactQueryProvider } from '@/lib/providers/ReactQueryProvider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

/**
 * Defines the root layout for the application, applying global styles, fonts, and context providers.
 *
 * Wraps all pages with GraphQL context and authentication redirect handling, and sets up the main HTML structure.
 *
 * @param children - The content to be rendered within the layout.
 */
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' className='dark'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className='fixed inset-0 -z-10 bg-[radial-gradient(1200px_800px_at_50%_-200px,rgba(59,130,246,0.08),transparent)]' />
                <ReactQueryProvider>
                    <ApolloWrapper>
                        <AuthRedirectListener />
                        <main className='flex min-h-dvh flex-col'>
                            {children}
                        </main>
                        <Toaster />
                    </ApolloWrapper>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
