version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
        container_name: frontend
        ports:
            - "3000:3000"
        restart: always
        environment:
            - NODE_ENV=development
            - WATCHPACK_POLLING=true
        depends_on:
            - auth
        develop:
            watch:
                - action: sync
                  path: ./frontend
                  target: /app
                  ignore:
                    - node_modules/
                - action: rebuild
                  path: ./frontend/package.json
    auth:
        build:
            context: ./backend/auth
            dockerfile: Dockerfile
        container_name: auth
        ports:
            - "8080:8080"
        volumes:
            - ./backend/auth:/app
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/personal_dashboard_auth
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: password
            JWT_SECRET: j20dfVx8xokTmxheH2kohSUW7b8+p+ObBvFoKMRV8Yvnpb4m1HrzrH+NFsy4sRmywNzc4FxqsJjoTS40TMSOTT1ALKmk5RxUq4hVtIGRNOQ+Z82TwUwozdIS3SquzACNRzjkvh71Ct0wCjuwdRQO+RbAabxPJWvS0R5B9QQolyq5LpqBUbPpxVDjpVhGBkNmBwu5ZO+/HkAvMp/d5yOQCH6vgp1NTZSXfECb8dyQxFz8fnVwvfx9aFlTDIubNvfwZaSwUPew/YLwvo8j6LXiNS3O8la3a8xfpOuegtXGBlGoosfPglPaxhMDCBsvazhbrjEBo4BUTH39CJGF7jU35M8sFzUfbkN5RCf2fV7dDho=
            JWT_ACCESS_EXPIRATION: 3600000
            JWT_REFRESH_EXPIRATION: 604800000
        depends_on:
            - db
    db:
        image: postgres:latest
        container_name: db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: personal_dashboard_auth
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
        driver: local
