services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}
      - GATEWAY_DOMAIN=${GATEWAY_DOMAIN}
    depends_on:
      - auth
    networks:
      - elk
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

  auth:
    build:
      context: ./backend/auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "8080:8080"
      - "5841:5841"
    # volumes:
    #   - ./backend/auth:/app
    networks:
      - elk
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      GATEWAY_SECRET: ${GATEWAY_SECRET}
      FRONTEND_DOMAIN: ${FRONTEND_DOMAIN}
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_REDIRECT_URI: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_REDIRECT_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_SCOPE: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_SCOPE}
      JAVA_OPTS: ${JAVA_OPTS}
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - elk
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  elasticsearch:
    profiles: ["elk"]
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.6
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elk
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 20s

  logstash:
    profiles: ["elk"]
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.16.6
    environment:
      - LOGSTASH_HTTP_HOST=${LOGSTASH_HTTP_HOST}
    ports:
      - "5044:5044"
    networks:
      - elk
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600/_node/stats"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 20s

  kibana:
    profiles: ["elk"]
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.16.6
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 20s

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "4000:4000"
      - "9229:9229"
    networks:
      - elk
    environment:
      - AUTH_URL=${AUTH_URL}
      - AUTH_REDIRECT_URL=${AUTH_REDIRECT_URL}
      - GATEWAY_SECRET=${GATEWAY_SECRET}
    depends_on:
      auth:
        condition: service_started

networks:
  elk:
    driver: bridge

volumes:
  db_data:
    driver: local
  esdata:
    driver: local
