services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}
      - NEXT_PUBLIC_GATEWAY_DOMAIN=${GATEWAY_DOMAIN}
    depends_on:
      - auth
    networks:
      - elk
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

  auth:
    build:
      context: ./backend/auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "8080:8080"
      - "5841:5841" # TODO: remove this port in production. create docker profiles
    networks:
      - elk
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      GATEWAY_SECRET: ${GATEWAY_SECRET}
      FRONTEND_DOMAIN: ${FRONTEND_DOMAIN}
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_REDIRECT_URI: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_REDIRECT_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_SCOPE: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_SCOPE}
      JAVA_OPTS: ${JAVA_OPTS}
      SENTRY_DSN: ${SENTRY_DSN_AUTH}
      SENTRY_SEND_DEFAULT_PII: ${SENTRY_SEND_DEFAULT_PII}
    depends_on:
      auth-db:
        condition: service_started

  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
    networks:
      - elk
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  elasticsearch:
    profiles: ["elk"]
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.6
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # temporary for development
      - logger.org.elasticsearch=error
    ports:
      - "9200:9200"
    networks:
      - elk
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 20s

  logstash:
    profiles: ["elk"]
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.16.6
    environment:
      - LOGSTASH_HTTP_HOST=${LOGSTASH_HTTP_HOST}
      - LOG_LEVEL=error
    ports:
      - "5044:5044"
    networks:
      - elk
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600/_node/stats"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 20s

  kibana:
    profiles: ["elk"]
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.16.6
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - LOGGING_ROOT_LEVEL=error
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 20s
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "4000:4000"
      - "9229:9229"
    networks:
      - elk    
    environment:
      - AUTH_URL=${AUTH_URL}
      - AUTH_REDIRECT_URL=${AUTH_REDIRECT_URL}
      - GATEWAY_SECRET=${GATEWAY_SECRET}
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}      
    depends_on:
      auth:
        condition: service_started
      widget-registry:
        condition: service_started
      notes:
        condition: service_started
      tasks:
        condition: service_started
  widget-registry:
    build:
      context: ./backend/widget-registry
      dockerfile: Dockerfile
    container_name: widget-registry
    ports:
      - "3001:3001"
    networks:
      - elk
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@widget-registry-db:5432/${POSTGRES_DB_WIDGET_REGISTRY}?schema=public
      - GATEWAY_SECRET=${GATEWAY_SECRET}
      - KAFKA_BROKERS=event-bus:9092
    restart: always
    depends_on:
      widget-registry-db:
        condition: service_started
      event-bus:
        condition: service_healthy
      kafka-topic-setup:
        condition: service_completed_successfully
    develop:
      watch:
        - action: sync
          path: ./backend/widget-registry
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/widget-registry/package.json
    volumes:
      - ./backend/widget-registry/prisma:/usr/src/app/prisma

  widget-registry-db:
    image: postgres:latest
    container_name: widget-registry-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_WIDGET_REGISTRY}
    networks:
      - elk
    ports:
      - "5433:5432"
    volumes:
      - widget_registry_db_data:/var/lib/postgresql/data

  notes:
    build:
      context: ./backend/notes
      dockerfile: Dockerfile
    container_name: notes
    ports:
      - "8000:8000"
    networks:
      - elk
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=8000
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@notes-db:5432/${POSTGRES_DB_NOTES}
      - SENTRY_DSN_NOTES=${SENTRY_DSN_NOTES}
      - SENTRY_SEND_DEFAULT_PII=${SENTRY_SEND_DEFAULT_PII}
      - KAFKA_BROKERS=event-bus:9092
    restart: always
    depends_on:
      notes-db:
        condition: service_started
      event-bus:
        condition: service_healthy
      kafka-topic-setup:
        condition: service_completed_successfully
    develop:
      watch:
        - action: sync
          path: ./backend/notes/src
          target: /app/src
          ignore:
            - __pycache__/
    volumes:
      - ./backend/notes/alembic/versions:/app/alembic/versions

  notes-db:
    image: postgres:latest
    container_name: notes-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NOTES}
    networks:
      - elk
    ports:
      - "5434:5432"
    volumes:
      - notes_db_data:/var/lib/postgresql/data

  tasks-db:
    image: postgres:latest
    container_name: tasks-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TASKS}
    networks:
      - elk
    ports:
      - "5435:5432"
    volumes:
      - tasks_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_TASKS}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  tasks:
    build:
      context: ./backend/tasks
      dockerfile: Dockerfile
    container_name: tasks
    ports:
      - "8001:8001"
    networks:
      - elk
    environment:
      - PORT=8001
      - ConnectionStrings__DefaultConnection=Host=tasks-db;Database=${POSTGRES_DB_TASKS};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${NODE_ENV}
      - GATEWAY_SECRET=${GATEWAY_SECRET}
      - KAFKA_BROKERS=event-bus:9092
    restart: always
    depends_on:
      tasks-db:
        condition: service_healthy
      event-bus:
        condition: service_healthy
      kafka-topic-setup:
        condition: service_completed_successfully
    volumes:
      - ./backend/tasks/Migrations:/app/Migrations

  event-bus:
    image: bitnami/kafka:latest
    container_name: event-bus
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@event-bus:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://event-bus:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elk

  kafka-topic-setup:
    image: bitnami/kafka:latest
    container_name: kafka-topic-setup
    depends_on:
      event-bus:
        condition: service_healthy
    command: >
      bash -c "
        kafka-topics.sh --bootstrap-server event-bus:9092 --create --if-not-exists --topic widget-deleted --partitions 1 --replication-factor 1
        echo 'Topics created successfully'
      "
    networks:
      - elk
    restart: "no"

  event-bus-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: event-bus-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BROKERS=event-bus:9092
    depends_on:
      event-bus:
        condition: service_healthy
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  auth_db_data:
    driver: local
  widget_registry_db_data:
    driver: local
  notes_db_data:
    driver: local
  tasks_db_data:
    driver: local
  esdata:
    driver: local
