services:
  nginx:
    volumes:
      - ./nginx/nginx.ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./ssl/key.pem:/etc/ssl/private/key.pem:ro
    ports:
      - "80:80"
      - "443:443"
